version: "3.8"

services:
    web:
        image: "${WEB_IMAGE}"
        command: gunicorn codeln3d.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - redis
    redis:
        restart: unless-stopped
        image: redis:7-alpine
        expose:
            - 6379
    celery:
        image: "${BEAT_IMAGE}"
        command: celery -A codeln3d worker -l info
        env_file:
            - ./.env
        depends_on:
            - redis
    celery-beat:
        image: "${BEAT_IMAGE}"
        command: celery -A codeln3d beat -l info
        env_file:
            - ./.env
        depends_on:
            - redis

    dashboard:
        image: "${DASH_IMAGE}"
        command: celery flower -A codeln3d --port=5555 --broker=redis://redis:6379/0
        expose:
            - 5555
        env_file:
            - ./.env
        depends_on:
            - web
            - redis
            - celery
            - celery-beat

    nginx:
        build:
            context: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
