version: "3.8"

services:
    web:
        build:
            context: ./apps
        command: gunicorn codeln3d.wsgi:application --bind 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - ./.env
    #     depends_on:
    #         - redis
    # redis:
    #     image: redis
    # celery:
    #     build:
    #         context: ./apps
    #     command: celery -A codeln3d worker -l info
    #     env_file:
    #         - ./.env
    #     depends_on:
    #         - redis
    # celery-beat:
    #     build:
    #         context: ./apps
    #     command: celery -A codeln3d beat -l info
    #     env_file:
    #         - ./.env
    #     depends_on:
    #         - redis

    # dashboard:
    #     build:
    #         context: ./apps
    #     command: celery flower -A codeln3d --port=5555 --broker=redis://redis:6379/0
    #     ports:
    #         - 5555:5555
    #     env_file:
    #         - ./.env
    #     depends_on:
    #         - web
    #         - redis
    #         - celery
    #         - celery-beat
