version: "3.8"

services:
    web:
        build: ./apps
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - redis
    redis:
        image: redis:alpine
    celery:
        build: ./apps
        command: celery -A core worker -l info
        env_file:
            - ./.env
        depends_on:
            - redis
    celery-beat:
        build: ./apps
        command: celery -A core beat -l info
        env_file:
            - ./.env
        depends_on:
            - redis

    dashboard:
        build: ./apps
        command: celery flower -A core --port=5555 --broker=redis://redis:6379/0
        ports:
            - 5555:5555
        env_file:
            - ./.env
        depends_on:
            - web
            - redis
            - celery
            - celery-beat
