version: "3.8"

services:
    web:
        build:
            context: ./apps
            dockerfile: Dockerfile.prod
            cache_from:
                - "${WEB_IMAGE}"
        image: "${WEB_IMAGE}"
        command: gunicorn codeln3d.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - redis
    redis:
        image: redis:7-alpine
    celery:
        build:
            context: ./apps
            cache_from:
                - "${CELERY_IMAGE}"
        image: "${CELERY_IMAGE}"
        command: celery -A codeln3d worker -l info
        env_file:
            - ./.env
        depends_on:
            - redis
    celery-beat:
        build:
            context: ./apps
            cache_from:
                - "${BEAT_IMAGE}"
        image: "${BEAT_IMAGE}"
        command: celery -A codeln3d beat -l info
        env_file:
            - ./.env
        depends_on:
            - redis

    dashboard:
        build:
            context: ./apps
            cache_from:
                - "${DASH_IMAGE}"
        image: "${DASH_IMAGE}"
        command: celery flower -A codeln3d --port=5555 --broker=redis://redis:6379/0
        expose:
            - 5555
        env_file:
            - ./.env
        depends_on:
            - web
            - redis
            - celery
            - celery-beat

    nginx:
        build:
            context: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
