# Generated by Django 4.2.7 on 2023-11-06 00:22

from django.db import (
    migrations,
)


class Migration(migrations.Migration):
    dependencies = [
        (
            "clnapp",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["id"],
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.AlterModelOptions(
            name="model3d",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Model3d",
                "verbose_name_plural": "Model3ds",
            },
        ),
    ]
