# Generated by Django 4.2.7 on 2023-11-06 08:18

from django.conf import (
    settings,
)
from django.db import (
    migrations,
)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "clnapp",
            "0002_alter_badge_options_alter_model3d_options",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={
                (
                    "user",
                    "badge",
                )
            },
        ),
    ]
