name: Deploy

on: 
  pull_request:
    branches: 
      - master
  workflow_run:
    workflows: ["build-and-push"]
    types: 
      - completed
env:
    # Default
    DEBUG: ${{ secrets.DEBUG }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    DJANGO_ALLOWED_HOSTS: ${{ secrets.ACTION_DJANGO_ALLOWED_HOSTS }}
    CELERY_BROKER: ${{ secrets.CELERY_BROKER }}
    CELERY_BACKEND: ${{ secrets.CELERY_BACKEND }}
    # AWS S3
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_STORAGE_BUCKET_NAME: ${{secrets.AWS_STORAGE_BUCKET_NAME}}
    # Docker images
    DOCKER_USER: ${{secrets.DOCKER_USER}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    REGISTRY: docker.io
    WEB_IMAGE: ${{ secrets.WEB_IMAGE }}
    CELERY_IMAGE: ${{ secrets.CELERY_IMAGE }}
    BEAT_IMAGE: ${{ secrets.BEAT_IMAGE }}
    DASH_IMAGE: ${{ secrets.DASH_IMAGE }}
    NGINX_IMAGE: ${{ secrets.NGINX_IMAGE }}
    # Nginx proxy
    VIRTUAL_HOST: ${{secrets.VIRTUAL_HOST}}
    VIRTUAL_PORT: ${{secrets.VIRTUAL_PORT}}
    # let encrypted
    DEFAULT_EMAIL: ${{secrets.DEFAULT_EMAIL}}

jobs:
    befor-deploy:
      name: Befor deploy
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      needs: push-image-to-docker-hub
      steps:
        - uses: actions/checkout@v3
        - name: Create env file
          run: |
            chmod +x ./apps/setup_env.ci.sh
            bash ./apps/setup_env.ci.sh
        - name: copy file via ssh key
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{secrets.DEPLOY_PUBLIC_IP_ADDRESS}}
            username: ${{secrets.SERVER_USER}}
            key: ${{secrets.PRIVATE_KEY}}
            port: 22
            source: "./nginx, ./.env, ./.env.proxy-companion, ./docker-compose.prod.yml"
            target: "/${{secrets.SERVER_USER}}/project/"

    deploy:
      runs-on: ubuntu-latest  # Utilisez l'image Ubuntu par défaut
      if: github.ref == 'refs/heads/master'
      needs: befor-deploy
      steps:
        - uses: actions/checkout@v3
        - name: docker login
          run: | # log into docker hub account
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTRY
        - name: Deploy using ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.DEPLOY_PUBLIC_IP_ADDRESS}}
            username: ${{secrets.SERVER_USER}}
            key: ${{secrets.PRIVATE_KEY}}
            port: 22
            script: |
              cd /${{secrets.SERVER_USER}}/project/
              export $(cat .env | xargs)
              docker pull push $WEB_IMAGE
              docker pull $NGINX_IMAGE
              docker pull $CELERY_IMAGE
              docker pull $BEAT_IMAGE
              docker pull $DASH_IMAGE
              docker-compose -f docker-compose.prod.yml down || true
              docker rm -vf $(docker ps -aq) || true
              docker rmi -f $(docker images -aq) || true
              docker-compose -f docker-compose.prod.yml up -d