name: Django CI

on: [pull_request, push]
env:
    DEBUG: ${{ secrets.DEBUG }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    DJANGO_ALLOWED_HOSTS: ${{ vars.ACTION_DJANGO_ALLOWED_HOSTS }}
    CELERY_BROKER: ${{ vars.CELERY_BROKER }}
    CELERY_BACKEND: ${{ vars.CELERY_BACKEND }}

jobs:
    test_project:
        runs-on: ubuntu-latest # operating system your code will run on
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - name: Run script file
              run: |
                  chmod +x ./apps/setup_env.sh
                  bash ./apps/setup_env.sh
                  cp ./apps/codeln3d/settings/base.ci.py ./apps/codeln3d/settings/base.py
            - run: cat ./apps/.env
            - run: pip install flake8
            - run: pip install setuptools
            - run: pip install -r apps/requirements.txt # install all our dependencies for the project
            - run: flake8 . # run flake8 test
            - run: |
                  cd apps/
                  python manage.py test
    next_job:
        runs-on: ubuntu-latest # operating system your code will run on
        needs: test_project
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: cat ./apps/codeln3d/settings/base.py
